global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'your@email.com'
    from: 'alert@email.com'
    smarthost: 'smtp.yourmail.com:587'
    auth_username: 'alert@email.com'
    auth_password: 'yourpassword'
    require_tls: true 